/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cloudwalk_cn_opencvdemo_OpenCVHelper */

#ifndef _Included_cloudwalk_cn_opencvdemo_OpenCVHelper
#define _Included_cloudwalk_cn_opencvdemo_OpenCVHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cloudwalk_cn_opencvdemo_OpenCVHelper
 * Method:    gray
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_cloudwalk_cn_opencvdemo_OpenCVHelper_gray
  (JNIEnv *, jclass, jintArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
